# Generated by Django 3.2.21 on 2023-09-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
